### ISSUE TITLE
how to add country

### ISSUE THREAD

**Issue by dannyid113** [adcar/zoomeye-search#13]
zoomeye   +country  is empty

**Comment by adcar** [comment]
Do something like
`python zoomeye.py -p 1 -q 'country:"US"'`

**Comment by madara19** [comment]
Any updates for this script i've been using it years ago !

**Comment by adcar** [comment]
@madara19 I don't understand what you're saying or how this relates to country filtering. I'm closing this issue since it's obviously inactive
